import Head from "next/head";
import Image from "next/image";
import NavBar from "@/components/Navbar";
import Main from "@/pages/landing/Main";
import About from "./about";


export default function Home() {
  return (
    <>
      <Head>
        <title>Curtis Wong | Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Main />
    </>
  );
}
